name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    name: greetings
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome!'' first issue'
        pr-message: 'Welcome!'' first pr'
